// Code generated by fabrica codegen init. DO NOT EDIT.
package resources

import (
	"fmt"

	"github.com/openchami/fabrica/pkg/codegen"
	"github.com/user/inventory-api/pkg/resources/device"
)

// RegisterAllResources registers all discovered resources with the generator.
// This file is auto-generated. Re-run 'fabrica codegen init' after adding resources.
func RegisterAllResources(gen *codegen.Generator) error {
	if err := gen.RegisterResource(&device.Device{}); err != nil {
		return fmt.Errorf("failed to register Device: %w", err)
	}

	return nil
}
