package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"github.com/bmcdonald3/inventory/pkg/resources/device"
)

// UpdateDeviceStatus performs a PUT /devices/{uid}/status request.
// This method is manually added to the client SDK to support the collector.
// It attaches to the existing 'Client' struct generated by Fabrica.
func (c *Client) UpdateDeviceStatus(ctx context.Context, uid string, status *device.DeviceStatus) (*Device, error) {

	// Wrap the status in the expected { "status": { ... } } payload
	payload := map[string]interface{}{
		"status": status,
	}

	jsonPayload, err := json.Marshal(payload)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal status payload: %w", err)
	}

	// Build the URL for the /status sub-resource
	// Based on your client, 'CreateDevice' is on the main client,
	// so we build the path manually.
	urlPath := fmt.Sprintf("/devices/%s/status", uid)

	req, err := c.NewRequest(ctx, http.MethodPut, urlPath, bytes.NewBuffer(jsonPayload))
	if err != nil {
		return nil, fmt.Errorf("failed to create UpdateStatus request: %w", err)
	}

	req.Header.Set("Content-Type", "application/json")

	// 'Device' is the standard resource response struct defined in the SDK
	var deviceResponse Device
	if err := c.Do(req, &deviceResponse); err != nil {
		return nil, fmt.Errorf("failed to execute UpdateStatus request: %w", err)
	}

	return &deviceResponse, nil
}